-- =============================================================================
-- Constituant - Database Schema
-- =============================================================================
--
-- French civic engagement platform: citizens vote on real legislation
-- and compare their votes with actual parliamentary outcomes.
--
-- MySQL 8.0+ | utf8mb4_unicode_ci | InnoDB
--
-- Usage:
--   mysql -u root -p constituant < database/schema.sql
--
-- Or create the DB first:
--   CREATE DATABASE constituant CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
--
-- Last updated: 2026-02-18
-- =============================================================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
SET NAMES utf8mb4;

-- =============================================================================
-- STORED PROCEDURE: update_bill_statuses
-- Called hourly by the auto_update_bill_statuses event.
-- Transitions bills between upcoming → voting_now → completed based on
-- their vote_datetime relative to now.
-- =============================================================================

DROP PROCEDURE IF EXISTS `update_bill_statuses`;

DELIMITER $$
CREATE PROCEDURE `update_bill_statuses`()
BEGIN
    DECLARE now_time DATETIME;
    SET now_time = NOW();

    -- Bills whose vote date has passed become 'completed'
    UPDATE `bills`
    SET `status` = 'completed'
    WHERE `vote_datetime` < now_time
      AND `status` != 'completed';

    -- Bills voting within the next 7 days become 'voting_now'
    UPDATE `bills`
    SET `status` = 'voting_now'
    WHERE `vote_datetime` >= now_time
      AND `vote_datetime` <= DATE_ADD(now_time, INTERVAL 7 DAY)
      AND `status` != 'voting_now'
      AND `status` != 'completed';

    -- Bills further than 7 days out stay/become 'upcoming'
    UPDATE `bills`
    SET `status` = 'upcoming'
    WHERE `vote_datetime` > DATE_ADD(now_time, INTERVAL 7 DAY)
      AND `status` != 'upcoming';
END$$
DELIMITER ;

-- =============================================================================
-- TABLE: bills
-- One row per legislative bill/dossier imported from any data source.
-- Vote counts (votes_for, votes_against, votes_abstain, votes_total) are
-- maintained automatically by triggers on the `votes` table.
-- =============================================================================

DROP TABLE IF EXISTS `bills`;

CREATE TABLE `bills` (
    `id`                       varchar(100)                              NOT NULL COMMENT 'Unique ID: source-slug-year (e.g. legifrance-api-jorfdole000050031920-2026)',
    `title`                    varchar(500)   COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Bill title',
    `summary`                  text           COLLATE utf8mb4_unicode_ci          COMMENT 'Original technical summary from source API',
    `ai_summary`               text           COLLATE utf8mb4_unicode_ci          COMMENT 'Citizen-friendly summary generated by Mistral AI',
    `mistral_ai_json_response` json                                      DEFAULT NULL COMMENT 'Full Mistral AI JSON: summary, pour, contre, concerne, theme, abstract',
    `full_text_url`            varchar(1000)  COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL to official full text on Légifrance or EUR-Lex',
    `theme`                    varchar(100)   COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Sans catégorie' COMMENT 'AI-classified theme',
    `ai_confidence`            decimal(3,2)                              DEFAULT NULL COMMENT 'Mistral confidence score (0.00–1.00)',
    `level`                    enum('france','eu') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Legislative level',
    `chamber`                  varchar(100)   COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Assemblée Nationale | Sénat | Parlement | European Parliament',
    `vote_datetime`            datetime                                  NOT NULL  COMMENT 'Scheduled parliamentary vote date (placeholder +30d for Légifrance dossiers)',
    `votes_for`                int UNSIGNED                              NOT NULL DEFAULT 0 COMMENT 'Citizen FOR votes (updated by trigger)',
    `votes_against`            int UNSIGNED                              NOT NULL DEFAULT 0 COMMENT 'Citizen AGAINST votes (updated by trigger)',
    `votes_abstain`            int UNSIGNED                              NOT NULL DEFAULT 0 COMMENT 'Citizen ABSTAIN votes (updated by trigger)',
    `votes_total`              int UNSIGNED                              NOT NULL DEFAULT 0 COMMENT 'Total citizen votes (updated by trigger)',
    `status`                   enum('upcoming','voting_now','completed') COLLATE utf8mb4_unicode_ci DEFAULT 'upcoming' COMMENT 'Updated hourly by event scheduler',
    `source`                   varchar(50)    COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'legifrance-api | eu-parliament | nosdeputes | lafabrique',
    `external_id`              varchar(100)   COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID from external source (e.g. JORFDOLE000050031920)',
    `created_at`               timestamp      NULL DEFAULT CURRENT_TIMESTAMP      COMMENT 'When bill was first imported',
    `updated_at`               timestamp      NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update',
    `ai_processed_at`          timestamp      NULL DEFAULT NULL                   COMMENT 'When Mistral AI classification completed',

    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_source_bill`    (`source`, `external_id`),
    KEY        `idx_status`            (`status`),
    KEY        `idx_level`             (`level`),
    KEY        `idx_theme`             (`theme`),
    KEY        `idx_vote_datetime`     (`vote_datetime`),
    KEY        `idx_source_external`   (`source`, `external_id`),
    KEY        `idx_active_bills`      (`status`, `vote_datetime`)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Legislative bills — imported from Légifrance, EU Parliament, etc.';

-- =============================================================================
-- TABLE: votes
-- One row per citizen vote. Citizen identity = IP address (anonymous).
-- UNIQUE(bill_id, voter_ip) enforces one vote per bill per person.
-- Triggers keep bills.votes_* counts in sync automatically.
-- =============================================================================

DROP TABLE IF EXISTS `votes`;

CREATE TABLE `votes` (
    `id`         int UNSIGNED                              NOT NULL AUTO_INCREMENT,
    `bill_id`    varchar(100)  COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'FK → bills.id',
    `vote_type`  enum('for','against','abstain') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Citizen vote choice',
    `voter_ip`   varchar(45)   COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'IPv4 or IPv6 (max 45 chars)',
    `user_agent` varchar(255)  COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Browser user-agent (for bot detection)',
    `voted_at`   timestamp     NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the vote was cast',

    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_vote`   (`bill_id`, `voter_ip`),
    KEY        `idx_bill_id`   (`bill_id`),
    KEY        `idx_voted_at`  (`voted_at`),
    KEY        `idx_voter_ip`  (`voter_ip`),

    CONSTRAINT `votes_ibfk_1`
        FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE CASCADE

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Citizen votes — one per bill per IP address';

-- =============================================================================
-- TRIGGERS: votes → bills counter sync
-- Keeps bills.votes_for/against/abstain/total accurate without application logic.
-- =============================================================================

DROP TRIGGER IF EXISTS `after_vote_insert`;
DROP TRIGGER IF EXISTS `after_vote_update`;
DROP TRIGGER IF EXISTS `after_vote_delete`;

DELIMITER $$

CREATE TRIGGER `after_vote_insert`
AFTER INSERT ON `votes`
FOR EACH ROW
BEGIN
    UPDATE `bills`
    SET
        `votes_for`     = `votes_for`     + IF(NEW.vote_type = 'for',     1, 0),
        `votes_against` = `votes_against` + IF(NEW.vote_type = 'against', 1, 0),
        `votes_abstain` = `votes_abstain` + IF(NEW.vote_type = 'abstain', 1, 0),
        `votes_total`   = `votes_total`   + 1
    WHERE `id` = NEW.bill_id;
END$$

CREATE TRIGGER `after_vote_update`
AFTER UPDATE ON `votes`
FOR EACH ROW
BEGIN
    -- Decrement old vote type
    UPDATE `bills`
    SET
        `votes_for`     = `votes_for`     - IF(OLD.vote_type = 'for',     1, 0),
        `votes_against` = `votes_against` - IF(OLD.vote_type = 'against', 1, 0),
        `votes_abstain` = `votes_abstain` - IF(OLD.vote_type = 'abstain', 1, 0)
    WHERE `id` = OLD.bill_id;

    -- Increment new vote type
    UPDATE `bills`
    SET
        `votes_for`     = `votes_for`     + IF(NEW.vote_type = 'for',     1, 0),
        `votes_against` = `votes_against` + IF(NEW.vote_type = 'against', 1, 0),
        `votes_abstain` = `votes_abstain` + IF(NEW.vote_type = 'abstain', 1, 0)
    WHERE `id` = NEW.bill_id;
END$$

CREATE TRIGGER `after_vote_delete`
AFTER DELETE ON `votes`
FOR EACH ROW
BEGIN
    UPDATE `bills`
    SET
        `votes_for`     = `votes_for`     - IF(OLD.vote_type = 'for',     1, 0),
        `votes_against` = `votes_against` - IF(OLD.vote_type = 'against', 1, 0),
        `votes_abstain` = `votes_abstain` - IF(OLD.vote_type = 'abstain', 1, 0),
        `votes_total`   = `votes_total`   - 1
    WHERE `id` = OLD.bill_id;
END$$

DELIMITER ;

-- =============================================================================
-- TABLE: import_logs
-- One row per cron run per source. Tracks fetched/new/updated/skipped counts
-- and any error messages. Used by logImportOperation() in fetcher-base.php.
-- =============================================================================

DROP TABLE IF EXISTS `import_logs`;

CREATE TABLE `import_logs` (
    `id`             int UNSIGNED                              NOT NULL AUTO_INCREMENT,
    `source`         varchar(50)   COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'legifrance-api | eu-parliament | nosdeputes | etc.',
    `status`         enum('success','partial','failed') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Overall run status',
    `bills_fetched`  int UNSIGNED                              DEFAULT 0  COMMENT 'Bills found in source API',
    `bills_new`      int UNSIGNED                              DEFAULT 0  COMMENT 'New bills inserted',
    `bills_updated`  int UNSIGNED                              DEFAULT 0  COMMENT 'Existing bills updated',
    `bills_skipped`  int UNSIGNED                              DEFAULT 0  COMMENT 'Bills skipped (dedup or filtered)',
    `errors_count`   int UNSIGNED                              DEFAULT 0  COMMENT 'Number of errors',
    `execution_time` decimal(8,2)                              DEFAULT NULL COMMENT 'Run duration in seconds',
    `error_messages` text          COLLATE utf8mb4_unicode_ci             COMMENT 'JSON array of error strings',
    `started_at`     timestamp     NULL DEFAULT CURRENT_TIMESTAMP         COMMENT 'Import start time',
    `completed_at`   timestamp     NULL DEFAULT NULL                      COMMENT 'Import completion time',

    PRIMARY KEY (`id`),
    KEY `idx_source`     (`source`),
    KEY `idx_started_at` (`started_at`)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Cron import operation logs';

-- =============================================================================
-- EVENT: auto_update_bill_statuses
-- Runs hourly to transition bill statuses (upcoming → voting_now → completed).
-- Requires MySQL Event Scheduler to be enabled:
--   SET GLOBAL event_scheduler = ON;
-- On o2switch (cPanel), enable via: MySQL → Event Scheduler
-- =============================================================================

DROP EVENT IF EXISTS `auto_update_bill_statuses`;

DELIMITER $$
CREATE EVENT `auto_update_bill_statuses`
    ON SCHEDULE EVERY 1 HOUR
    STARTS CURRENT_TIMESTAMP
    ON COMPLETION NOT PRESERVE
    ENABLE
    COMMENT 'Hourly bill status transitions: upcoming → voting_now → completed'
DO
    CALL update_bill_statuses()$$
DELIMITER ;
